version: '3.4'

services:

  chat.api:
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      PostgresDatabaseConnection : Server=postgreDb,5432;Database=GPTChat;User Id=ilya.maximov11@gmail.com;Password=bb5fc9f6-bd13-4dfb-859e-a8cfe65d3c81;
      RedisDatabaseConnection : redis://:bb5fc9f6-bd13-4dfb-859e-a8cfe65d3c81@redisDb:6379
      JWTSecretKey : 4fef10f1-788b-4bcd-a5e4-79fad1a142a1
      JWTIssuer : Chat.API
      JWTAudience : Chat.API
      JWTDuration : 10
      JWTLoginProvider: Chat.APIProvider
      JWTRefreshToken: RefreshToken
    ports:
      - 5000:80
    restart: always
    depends_on:
      - redisDb
      - postgreDb

  redisDb:
    environment:
      REDIS_PASSWORD : bb5fc9f6-bd13-4dfb-859e-a8cfe65d3c81
    volumes:
      - redis_data:/data
    restart: always

  postgreDb:
    environment:
      POSTGRES_PASSWORD: bb5fc9f6-bd13-4dfb-859e-a8cfe65d3c81
      POSTGRES_USER: ilya.maximov11@gmail.com
      POSTGRES_DB: GPTChat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ilya.maximov11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - 5431:80
    volumes:
      - pgadmin_data:/root/.pgadmin
    restart: always

volumes:
  redis_data:
  postgres_data:
  pgadmin_data: