version: '3.4'

services:
      
  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: src/Services/Chat.API/Chat.API/Dockerfile

  redisDb:
    image: redis:alpine
    
  postgreDb:
    image: postgres:alpine

  pgadmin:
    image: dpage/pgadmin4

